services:
  traefik:
    command:
      - "--providers.swarm=true"
      - "--providers.swarm.exposedByDefault=false"
      - "--providers.swarm.network=pvz_net"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=admin@sdsprinter.ru"
      - "--certificatesresolvers.le.acme.storage=/data/acme.json"
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "443:443"
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.traefik-svc.loadbalancer.server.port=8080"

  web:
    command: sh /backend/entrypoint.prod.sh
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pvz-api.rule=Host(`sdsprinter.ru`) && (PathPrefix(`/api`) || PathPrefix(`/admin`))"
        - "traefik.http.routers.pvz-api.entrypoints=websecure"
        - "traefik.http.routers.pvz-api.tls.certresolver=le"
        - "traefik.http.routers.pvz-api.priority=10"
        - "traefik.http.services.pvz-web-svc.loadbalancer.server.port=8000"
        - "traefik.http.routers.pvz-api.service=pvz-web-svc"

  frontend:
    deploy:
      replicas: 1
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pvz-spa.rule=Host(`sdsprinter.ru`)"
        - "traefik.http.routers.pvz-spa.entrypoints=websecure"
        - "traefik.http.routers.pvz-spa.tls.certresolver=le"
        - "traefik.http.routers.pvz-spa.priority=1"
        - "traefik.http.services.pvz-spa-svc.loadbalancer.server.port=80"
        - "traefik.http.routers.pvz-spa.service=pvz-spa-svc"

  minio:
    environment:
      MINIO_DOMAIN: "s3.sdsprinter.ru"
      MINIO_BROWSER_REDIRECT_URL: "https://console.s3.sdsprinter.ru"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.minio-api.rule=Host(`s3.sdsprinter.ru`) || Host(`static.s3.sdsprinter.ru`) || Host(`media.s3.sdsprinter.ru`)"
        - "traefik.http.routers.minio-api.entrypoints=websecure"
        - "traefik.http.routers.minio-api.tls.certresolver=le"
        - "traefik.http.routers.minio-api.service=minio-api-svc"
        - "traefik.http.services.minio-api-svc.loadbalancer.server.port=9000"
        - "traefik.http.routers.minio-console.rule=Host(`console.s3.sdsprinter.ru`)"
        - "traefik.http.routers.minio-console.entrypoints=websecure"
        - "traefik.http.routers.minio-console.tls.certresolver=le"
        - "traefik.http.routers.minio-console.service=minio-console-svc"
        - "traefik.http.services.minio-console-svc.loadbalancer.server.port=9001"

  bot:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  celery-worker:
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  celery-beat:
    deploy:
      replicas: 1  # ⚠️ строго 1, иначе задачи задублируются
      restart_policy:
        condition: on-failure