volumes:
  traefik_data:
  # Подключаем твой старый волюм базы
  postgres_data:
    external: true
    name: pvzbot_postgres_data
  redis_data:
  minio_data:
    external: true
    name: pvzbot_minio_data

services:
  traefik:
    container_name: pvz-traefik
    image: traefik:latest
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=admin@sdsprinter.ru"
      - "--certificatesresolvers.le.acme.storage=/data/acme.json"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Монтируем файл напрямую для SSL
      - ./acme.json:/data/acme.json 

  db:
    container_name: pvz-db
    image: postgres:16.2
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${SQL_USER}"]
      interval: 10s

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    stop_grace_period: 30s 
    deploy:
      replicas: 2
      update_config:
        order: start-first
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/schema/"]
      interval: 15s
      start_period: 30s
    command: sh /backend/entrypoint.prod.sh
    env_file: .env 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pvz-api.rule=Host(`sdsprinter.ru`) && (PathPrefix(`/api`) || PathPrefix(`/admin`))"
      - "traefik.http.routers.pvz-api.entrypoints=websecure"
      - "traefik.http.routers.pvz-api.tls.certresolver=le"
      - "traefik.http.routers.pvz-api.priority=10"
      - "traefik.http.services.pvz-web-svc.loadbalancer.server.port=8000"
    depends_on:
      db: { condition: service_healthy }
      redis: { condition: service_healthy }

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod

    restart: unless-stopped
    deploy:
      update_config:
        order: start-first
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pvz-spa.rule=Host(`sdsprinter.ru`)"
      - "traefik.http.routers.pvz-spa.entrypoints=websecure"
      - "traefik.http.routers.pvz-spa.tls.certresolver=le"
      - "traefik.http.routers.pvz-spa.priority=1"
      - "traefik.http.services.pvz-frontend-svc.loadbalancer.server.port=80"

  minio:
    image: minio/minio:latest
    restart: always
    env_file: .env
    environment:
      MINIO_DOMAIN: "s3.sdsprinter.ru"
      MINIO_BROWSER_REDIRECT_URL: "https://console.s3.sdsprinter.ru"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio-api.rule=Host(`s3.sdsprinter.ru`) || Host(`static.s3.sdsprinter.ru`) || Host(`media.s3.sdsprinter.ru`)"
      - "traefik.http.routers.minio-api.entrypoints=websecure"
      - "traefik.http.routers.minio-api.tls.certresolver=le"
      - "traefik.http.routers.minio-api.service=minio-api-svc"
      - "traefik.http.routers.minio-console.rule=Host(`console.s3.sdsprinter.ru`)"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.tls.certresolver=le"
      - "traefik.http.routers.minio-console.service=minio-console-svc"
      - "traefik.http.services.minio-api-svc.loadbalancer.server.port=9000"
      - "traefik.http.services.minio-console-svc.loadbalancer.server.port=9001"

  # Остальные сервисы (bot, celery)
  bot:
    build: ./bot
    restart: always
    env_file: .env 
    depends_on:
      web: { condition: service_healthy }

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A core worker -l info
    env_file: .env
    depends_on:
      redis: { condition: service_healthy }

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A core beat -l info
    env_file: .env
    depends_on:
      redis: { condition: service_healthy }
